name: "first workflow"
on: 
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
      - qa
      
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                node-version: 24
                cache: npm

            - name: setup not js
              uses: actions/setup-node@v4
              with:
                node-version: 24
                cache: npm


            - name: install dependency
              run: npm ci

            - name: run es linting
              run: npm run lint

            - name: make react build 
              run: npm run build